/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CombinedHistoryRouteImport } from './routes/combined-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistorySymbolRouteImport } from './routes/history.$symbol'
import { Route as AccountNameRouteImport } from './routes/account.$name'

const CombinedHistoryRoute = CombinedHistoryRouteImport.update({
  id: '/combined-history',
  path: '/combined-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySymbolRoute = HistorySymbolRouteImport.update({
  id: '/history/$symbol',
  path: '/history/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNameRoute = AccountNameRouteImport.update({
  id: '/account/$name',
  path: '/account/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combined-history': typeof CombinedHistoryRoute
  '/account/$name': typeof AccountNameRoute
  '/history/$symbol': typeof HistorySymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combined-history': typeof CombinedHistoryRoute
  '/account/$name': typeof AccountNameRoute
  '/history/$symbol': typeof HistorySymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combined-history': typeof CombinedHistoryRoute
  '/account/$name': typeof AccountNameRoute
  '/history/$symbol': typeof HistorySymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combined-history' | '/account/$name' | '/history/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combined-history' | '/account/$name' | '/history/$symbol'
  id:
    | '__root__'
    | '/'
    | '/combined-history'
    | '/account/$name'
    | '/history/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombinedHistoryRoute: typeof CombinedHistoryRoute
  AccountNameRoute: typeof AccountNameRoute
  HistorySymbolRoute: typeof HistorySymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/combined-history': {
      id: '/combined-history'
      path: '/combined-history'
      fullPath: '/combined-history'
      preLoaderRoute: typeof CombinedHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$symbol': {
      id: '/history/$symbol'
      path: '/history/$symbol'
      fullPath: '/history/$symbol'
      preLoaderRoute: typeof HistorySymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$name': {
      id: '/account/$name'
      path: '/account/$name'
      fullPath: '/account/$name'
      preLoaderRoute: typeof AccountNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombinedHistoryRoute: CombinedHistoryRoute,
  AccountNameRoute: AccountNameRoute,
  HistorySymbolRoute: HistorySymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
